nix: Allow legacy CLI to handle nixpkgs reference
On a system which does not rely on channels, this allows resolving the
<nixpkgs> lookup path to the Nixpks flake. Without it, the following
error is thrown:

  nix-repl> <nixpkgs>
  error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

References:
- https://nix.dev/manual/nix/2.24/release-notes/rl-2.13
- NixOS/nix#7026
- DeterminateSystems/nix-installer#270