nix: Update determinate flake
determinate-nixd 0.37.2

Required a manual migration on macOS:

  error: Determinate needs migration, aborting activation
  Determinate now manages the Nix installation independently of the
  nix-darwin module.

  Please download and run the macOS installer from
  <https://docs.determinate.systems/getting-started/individuals> and then
  run `darwin-rebuild switch` again to migrate your installation.