pkg: Add 'keymap-drawer' to ZMK devShell
nixpkgs needs to be updated due to a build failure on macOS:

  ImportError: dlopen({{storeDir}}/lib/python3.13/site-packages/tree_sitter_devicetree/_binding.cpython-313-darwin.so, 0x0002): Library not loaded: parser
    Referenced from: <F0D5A9F8-FECD-3275-A29C-121AABBC74EC> {{storeDir}}/lib/python3.13/site-packages/tree_sitter_devicetree/_binding.cpython-313-darwin.so
    Reason: tried: 'parser' (no such file), '/System/Volumes/Preboot/Cryptexes/OSparser' (no such file), 'parser' (no such file), '/usr/local/lib/parser' (no such file), '/usr/lib/parser' (no such file, not in dyld cache), '//parser' (no such file), '/System/Volumes/Preboot/Cryptexes/OS//parser' (no such file), '//parser' (no such file), '/usr/local/lib/parser' (no such file), '/usr/lib/parser' (no such file, not in dyld cache)

Because zephyr-nix requires python310, nixpkgs needs to remain below the
revision NixOS/nixpkgs@77ca080475df714d3ea0f2d438eb1494efb208ac for the
time being.